//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGiaoHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int MaDH { get; set; }
        public string DiaChiNhanHang { get; set; }
        public string PhuongNhanHang { get; set; }
        public string QuanNhanHang { get; set; }
        public string TenNguoiNhanHang { get; set; }
        public string SDTNguoiNhanHang { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public string PhuongGiaoHang { get; set; }
        public string QuanGiaoHang { get; set; }
        public Nullable<int> PhiShip { get; set; }
    }
}
