//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGiaoHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CSDLQuanHuyenPhuongXaTPHCMEntities : DbContext
    {
        public CSDLQuanHuyenPhuongXaTPHCMEntities()
            : base("name=CSDLQuanHuyenPhuongXaTPHCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhuongXa> PhuongXas { get; set; }
        public virtual DbSet<QuanHuyen> QuanHuyens { get; set; }
    
        public virtual ObjectResult<TimPhuongXaTheoQuanHuyen_Result> TimPhuongXaTheoQuanHuyen(string quan)
        {
            var quanParameter = quan != null ?
                new ObjectParameter("Quan", quan) :
                new ObjectParameter("Quan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimPhuongXaTheoQuanHuyen_Result>("TimPhuongXaTheoQuanHuyen", quanParameter);
        }
    }
}
