//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGiaoHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongXa
    {
        public int STT { get; set; }
        public string TenQuanHuyen { get; set; }
        public string TenPhuongXa { get; set; }
    }
}
